### ISSUE TITLE
Activate axolotl as client to Android Version

### ISSUE THREAD

**Issue by NeroBurner** [nanu-c/axolotl#151]
**Is your feature request related to a problem? Please describe.**
I wan't to tinker with the new pinephone and use axolotl as signal client. But I don't want to deactivate the Signal-Android client. I want to use both phones with the same signal-account

**Describe the solution you'd like**
I'd like to activate Axolotl like the desktop client and continue to use the Android signal as main instance

**Describe alternatives you've considered**
none

**Additional context**
This would be a nice feature also for tablets. I was not able to have the Android tablet and the Android phone connected with the same signal account. With axolotl (in a desktop/client activation mode) this would be possible

**Comment by Blackoverflow** [comment]
There is a big difference between desktop client and main instance clients.
Both functions in one app would be hard to code and maintain.
I think it would be better to create a new app for that. A mobile device implementation for the signal desktop client.
Since https://github.com/signalapp/Signal-Desktop is written in JavaScript/TypeScript, it may even be easier to build a mobile app from a fork...
