### ISSUE TITLE
[Groupmessage] Receiving side gets message twice

### ISSUE THREAD

**Issue by joopdo** [nanu-c/axolotl#158]
Duplicate messages on 0.8.3 just now. Receiving side gets message twice.
Signal desktop shows message 8 times

_Originally posted by @joopdo in https://github.com/nanu-c/axolotl/issues/35#issuecomment-665502830_

**Comment by Flaburgan** [comment]
Those are group messages right? I guess there is 8 (or 9 including you) members in the group?

**Comment by joopdo** [comment]
Thank you for replying. 

There are 7 members in the group including me.
Let me know if you need any other information.

**Comment by Flaburgan** [comment]
Can you please confirm that this only happens with group chat, and edit the title if so.

**Comment by joopdo** [comment]
Checked and confirmed.

**Comment by Flaburgan** [comment]
@nanu-c I never had feedback from my contacts that my group messages are received twice, but I can confirm that in Signal desktop client, **for some groups only**, every message I send from Axolotl is displayed X times, where X is the number of the members of the group. Can you please have a look at that problem?

**Comment by Blackoverflow** [comment]
Axolotl sends one message for each group member to the Signal desktop client.
I have two ideas, whats wrong with that:

1. Axolotl should only send one message to the desktop client, regardless of the number of recipients.

2. There is some id field, that has to be equal on all these messages, so that the duplicates are hidden on signal desktop client.

**Comment by nanu-c** [comment]
Solved in 0.8.6
