### ISSUE TITLE
A new conversation is created for groups with users with the new UUID

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#327]
Two conversations for the same group are then in the home screen.

**Comment by nanu-c** [comment]
In order to fix this, are all new messages now in the new group? IS the title correct in the group? What happens, when another group member updates the group?

**Comment by nanu-c** [comment]
Is it related with sending messages with signal desktop?

**Comment by Flaburgan** [comment]
I don't know what happens if another member update the group.
At first it doesn't look related to Signal desktop. What happened:
- I wrote a message to a contact with Axolotl 0.9.5
- He had an "encrypted reset“ message showing that we correctly switched to uuid
- He wrote a message in a group in which I still have non uuid contacts
- The message is displayed in a new thread in Axolotl, with the same title and same contacts

**Comment by fabrei** [comment]
I see the same behaviour. Or I see two of them which are described in the last comment.

> He had an "encrypted reset“ message showing that we correctly switched to uuid

I saw that today as well with axolotl 0.9.5. On the desktop version there is everything fine. But it was at least with one contact. Another contact I chatted with, in axolotl, some seconds later, I had no problem with this "encrypted reset" thing. Is there any idea to fix it? I already reset the session in axolotl, but it didn't work. And after chatting with this contact via the desktop app and switching to axolotl again it doesn't work.

> The message is displayed in a new thread in Axolotl, with the same title and same contacts

Some days ago I was wondering why there was this second conversation of a group I already had in my list. The members and the title of the group are the same as the "old" group. It is not related to the desktop version. There I only have one of this group. And I don't know what happens when another member updates the group.

Do these two problems have the same reason?
